### ISSUE TITLE
Vagrant Development Environment

### ISSUE THREAD

**Issue by user404d** [MST-ACM/acm.mst.edu#11]
Create vagrant config for acm.mst.edu so that development is simpler. The vm should include all dependencies and be consistent with 'production'.

**Comment by user404d** [comment]
@kevinschoonover do you have an idea which OS we would be using for production? (I assume ubuntu 14.x.x but don't know for sure)

**Comment by kevinschoonover** [comment]
@user404d All my servers are Debian so I would do Debian for continuity sake.

**Comment by user404d** [comment]
I'm going to close this issue for now and when new features need to be added then we will open this bad boy back up.
