### ISSUE TITLE
Favicon Design

### ISSUE THREAD

**Issue by kevinschoonover** [MST-ACM/acm.mst.edu#23]
# Description
Design a favicon for the website

**Comment by ClayMav** [comment]
Do we want this icon to just be the ACM logo? Should this be completely custom?

**Comment by kevinschoonover** [comment]
I would prefer it to be custom, but the ACM logo works for now.

**Comment by ClayMav** [comment]
How much wiggle room do we get on rebranding our ACM?

**Comment by kevinschoonover** [comment]
Closed in #30
